### ISSUE TITLE
POWR2 - instantaneous Voltage, Current & Power values.

### ISSUE THREAD

**Issue by jinx1953** [ottoszika/node-red-contrib-ewelink#86]
Hello, using the eWeLink app. it is possible to view the instantaneous values of the Voltage, Current & Power, from the POWR2.
The accumulated Energy Consumption kWh (power usage over time) is useful, the instantaneous  values would be additionally useful, and in someways more useful, on NodeRed, where decisions could be made on, say overcurrent monitoring, Voltage monitoring (voltage drops causing failure) or power monitoring for load shedding.
I feel sure many would find this useful & and it is available in Tasmota :
Message | Unit | Description

TotalStartTime | Date | DateTime of calculation for Total
Total | kWh | Total Energy usage including Today
Yesterday | kWh | Total Energy usage between 00:00 and 24:00 yesterday
Today | kWh | Total Energy usage today from 00:00 until now
Period | Wh | Energy usage between previous message and now
Power | W | Current effective power load
ApparentPower | W | Power load on the cable = sqrt(Power^2 + ReactivePower^2)
ReactivePower | W | Reactive load
Factor |   | The ratio of the real power flowing to the load to the apparent power in the circuit
Voltage | V | Current line voltage
Current | A | Current line current

Is it possible for you to implement this feature?

So that out of the box Sonoff POWR2 can be used without re-flashing.
That is the value of your NodeRed contribution no re-flashing!

Thank you for what you have done it is great so far.

😎👍

**Comment by Asimuz** [comment]
Hi,

I just installed "node-red-contrib-ewelink" and it is great, really appreciated!

I have a farm with an offgrid solar system distributing power to four tenants, all with POWR2s into their respective houses.

It would be really great to be able to monitor the tenants continuous consumption and have a Node Red dashboard with gauges showing their "data" on their wall mounted tablets. 

They already use Ewelink app for installed Sonoff products.
To change to Tasmota would be a real challenge for them since they aren't so technically skilled ;-).

Thanks in advance!

**Comment by milesdream** [comment]
Hi, I dont find the POWR2 in the Devicelist . What can I do, I would like to Check and Record  the Grid Voltage from the Solar System. Thanks in advance
